- name: Test background
  uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
  with:
    ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
    password: "DKBOTZ" # You can also put the password in secrets as you wish.
    #foreground: false
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with ngrok debugging enabled'
        required: false
        default: false
